# Application bindings
bind = SUPER, RETURN, exec, kitty
bind = SUPER SHIFT, F, exec, dolphin
bind = SUPER SHIFT, L, exec, librewolf --browser
bind = SUPER ALT SHIFT, L, exec, librewolf --private-window
bind = SUPER, SPACE, exec, wofi --show drun
bind = SUPER, W, killactive
bind = $mainMod, ESCAPE, exec, command -v hyprshutdown >/dev/null 2>&1 && hyprshutdown || hyprctl dispatch exit

# Volume bindings
#bind = SUPER, F7, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 10%- && notify-send "Volume" "$(wpctl get-volume @DEFAULT_AUDIO_SINK@ | awk '{print $2*100"%"}')"

#bind = SUPER, F8, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 10%+ && notify-send "Volume" "$(wpctl get-volume @DEFAULT_AUDIO_SINK@ | awk '{print $2*100"%"}')"

#bind = SUPER CTRL, F7, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%- && notify-send "Volume" "$(wpctl get-volume @DEFAULT_AUDIO_SINK@ | awk '{print $2*100"%"}')"

#bind = SUPER CTRL, F8, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+ && notify-send "Volume" "$(wpctl get-volume @DEFAULT_AUDIO_SINK@ | awk '{print $2*100"%"}')"

#bind = SUPER, F6, exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle && notify-send "Volume" "Mute toggled"

# Brightness bindings
bind = SUPER, F1, exec, brightnessctl set 10%- && notify-send "Brightness" "$(brightnessctl g)"

bind = SUPER, F2, exec, brightnessctl set +10% && notify-send "Brightness" "$(brightnessctl g)"

bind = SUPER CTRL, F1, exec, brightnessctl set 5%- && notify-send "Brightness" "$(brightnessctl g)"

bind = SUPER CTRL, F2, exec, brightnessctl set +5% && notify-send "Brightness" "$(brightnessctl g)"
