# Application bindings
bind = SUPER, RETURN, exec, kitty
bind = SUPER SHIFT, F, exec, dolphin
bind = SUPER SHIFT, L, exec, librewolf --browser
bind = SUPER ALT SHIFT, L, exec, librewolf --private-window
bind = SUPER, SPACE, exec, wofi --show drun
bind = SUPER, W, killactive
bind = $mainMod, ESCAPE, exec, command -v hyprshutdown >/dev/null 2>&1 && hyprshutdown || hyprctl dispatch exit

# Volume bindings
#bind = SUPER, F7, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 10%- && notify-send "Volume" "$(wpctl get-volume @DEFAULT_AUDIO_SINK@ | awk '{print $2*100"%"}')"

#bind = SUPER, F8, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 10%+ && notify-send "Volume" "$(wpctl get-volume @DEFAULT_AUDIO_SINK@ | awk '{print $2*100"%"}')"

#bind = SUPER CTRL, F7, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%- && notify-send "Volume" "$(wpctl get-volume @DEFAULT_AUDIO_SINK@ | awk '{print $2*100"%"}')"

#bind = SUPER CTRL, F8, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+ && notify-send "Volume" "$(wpctl get-volume @DEFAULT_AUDIO_SINK@ | awk '{print $2*100"%"}')"

#bind = SUPER, F6, exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle && notify-send "Volume" "Mute toggled"

# Brightness submap (10% step)
# Trigger: SUPER + CTRL + F1
bind = SUPER CTRL, F1, submap, brightness
submap = brightness
binde = , up, exec, sahs-brightness up 10
binde = , down, exec, sahs-brightness down 10
bind = , c, exec, sahs-brightness get
bind = , m, exec, sahs-brightness max
bind = , catchall, submap, reset
submap = reset

# Brightness submap (5% step)
# Trigger: SUPER + CTRL + ALT + F1
bind = SUPER CTRL ALT, F1, submap, brightness5
submap = brightness5
binde = , up, exec, sahs-brightness up 5
binde = , down, exec, sahs-brightness down 5
bind = , c, exec, sahs-brightness get
bind = , m, exec, sahs-brightness max
bind = , catchall, submap, reset
submap = reset
